use_frameworks!

target 'SwiftBaseLibrary_Example' do
    
    inhibit_all_warnings!
    
  pod 'SwiftBaseLibrary', :path => '../'
  

  target 'SwiftBaseLibrary_Tests' do
    inherit! :search_paths

    
  end
end
